// Command speccheck provides two modes for Canvas API spec compliance.
//
//	-sync     parses all .ai/canvas-lms-docs/*.md endpoint declarations and
//	          writes testdata/spec/canvas_endpoints.json
//
//	-coverage prints a coverage gap report and writes /tmp/canvas_coverage_gap.md
//
// The .ai/canvas-lms-docs directory uses four endpoint declaration formats:
//
//	Format 1a (structured scope line with backtick):
//	  **Scope:** `url:METHOD|/api/v1/path`  or  Scope: `url:METHOD|/api/v1/path`
//
//	Format 1b (structured scope line without backtick -- italic markdown):
//	  *Scope: url:METHOD|/api/v1/path*
//
//	Format 2 (backtick inline code):
//	  `GET /api/v1/path`
//
//	Format 3 (bare method on its own line):
//	  GET /api/v1/path
//
// All four are harvested and deduplicated.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Endpoint is a single documented Canvas API endpoint.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

// Manifest is the committed inventory of documented Canvas API endpoints.
type Manifest struct {
	GeneratedNote string     `json:"generated_note"`
	Source        string     `json:"source"`
	Endpoints     []Endpoint `json:"endpoints"`
}

const (
	docsDir      = ".ai/canvas-lms-docs"
	manifestPath = "testdata/spec/canvas_endpoints.json"
	apiSrcDir    = "internal/api"
	coverageOut  = "/tmp/canvas_coverage_gap.md"
)

// urlScopeRe matches Canvas scope declarations in all variants:
//   - Format 1a: backtick url:METHOD|/api/... backtick
//   - Format 1b: *Scope: url:METHOD|/api/...* (italic, used in discussion-topics.md)
//
// The url:METHOD|path pattern terminates at whitespace or closing delimiters.
var urlScopeRe = regexp.MustCompile(`url:([A-Z]+)\|(/api/[^\s` + "`" + `*"<>\)]+)`)

// backtickMethodRe matches Format 2: `METHOD /api/...`
var backtickMethodRe = regexp.MustCompile("`" + `(GET|POST|PUT|DELETE|PATCH|HEAD) (/api/v[0-9][^` + "`" + `]*)` + "`")

// bareMethodRe matches Format 3: bare "METHOD /api/..." at the start of a line.
var bareMethodRe = regexp.MustCompile(`(?m)^(GET|POST|PUT|DELETE|PATCH|HEAD) (/api/v[0-9][^\s]*)`)

func main() {
	syncFlag := flag.Bool("sync", false, "parse .ai/canvas-lms-docs and write testdata/spec/canvas_endpoints.json")
	coverFlag := flag.Bool("coverage", false, "print coverage gap report and write /tmp/canvas_coverage_gap.md")
	flag.Parse()

	switch {
	case *syncFlag:
		if err := runSync(); err != nil {
			fmt.Fprintln(os.Stderr, "speccheck -sync:", err)
			os.Exit(1)
		}
	case *coverFlag:
		if err := runCoverage(); err != nil {
			fmt.Fprintln(os.Stderr, "speccheck -coverage:", err)
			os.Exit(1)
		}
	default:
		flag.Usage()
		os.Exit(2)
	}
}

// runSync parses all .md endpoint declarations and writes the manifest.
func runSync() error {
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		return fmt.Errorf("reading %s: %w", docsDir, err)
	}

	seen := map[string]bool{}
	var endpoints []Endpoint

	add := func(method, path string) {
		// Strip query strings, fragments, and trailing globs from doc paths.
		if i := strings.IndexAny(path, "?#"); i >= 0 {
			path = path[:i]
		}
		// Remove trailing wildcard segments that appear in some doc paths.
		path = strings.TrimSuffix(path, "/*full_path")
		path = strings.TrimRight(path, "/")
		if path == "" || !strings.HasPrefix(path, "/api/") {
			return
		}
		key := method + "|" + path
		if seen[key] {
			return
		}
		seen[key] = true
		endpoints = append(endpoints, Endpoint{Method: method, Path: path})
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(docsDir, e.Name()))
		if err != nil {
			return err
		}
		text := string(data)

		// Format 1 (backtick or italic): url:METHOD|/api/.../path
		for _, m := range urlScopeRe.FindAllStringSubmatch(text, -1) {
			add(m[1], m[2])
		}

		// Format 2: `METHOD /api/...`
		for _, m := range backtickMethodRe.FindAllStringSubmatch(text, -1) {
			add(m[1], m[2])
		}

		// Format 3: bare METHOD /api/... on its own line
		for _, m := range bareMethodRe.FindAllStringSubmatch(text, -1) {
			add(m[1], m[2])
		}
	}

	if len(endpoints) == 0 {
		return fmt.Errorf("parsed 0 endpoints from %s \u2014 doc format may have changed", docsDir)
	}

	sort.Slice(endpoints, func(i, j int) bool {
		if endpoints[i].Path != endpoints[j].Path {
			return endpoints[i].Path < endpoints[j].Path
		}
		return endpoints[i].Method < endpoints[j].Method
	})

	man := Manifest{
		GeneratedNote: "Auto-generated by tools/speccheck -sync. Do not edit manually.",
		Source:        docsDir,
		Endpoints:     endpoints,
	}

	if err := os.MkdirAll(filepath.Dir(manifestPath), 0o750); err != nil {
		return err
	}
	out, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(manifestPath, append(out, '\n'), 0o644); err != nil { // #nosec G306 -- committed spec manifest, world-readable by design
		return err
	}
	fmt.Printf("speccheck: %d documented endpoints -> %s\n", len(endpoints), manifestPath)
	return nil
}

// runCoverage reports which documented endpoints have no matching CLI path.
func runCoverage() error {
	man, err := loadManifest()
	if err != nil {
		return err
	}

	cliPaths, err := harvestCLIPaths(apiSrcDir)
	if err != nil {
		return fmt.Errorf("harvesting CLI paths from %s: %w", apiSrcDir, err)
	}

	// Build normalized CLI set.
	cliNorm := map[string]bool{}
	for _, p := range cliPaths {
		cliNorm[normalizePath(p)] = true
	}

	// Group documented endpoints by first resource segment.
	type resourceGap struct {
		resource    string
		implemented int
		total       int
		missing     []string
	}
	byResource := map[string]*resourceGap{}
	for _, ep := range man.Endpoints {
		seg := firstSegment(ep.Path)
		if _, ok := byResource[seg]; !ok {
			byResource[seg] = &resourceGap{resource: seg}
		}
		rg := byResource[seg]
		rg.total++
		norm := normalizePath(ep.Path)
		if cliNorm[norm] {
			rg.implemented++
		} else {
			rg.missing = append(rg.missing, fmt.Sprintf("%s %s", ep.Method, ep.Path))
		}
	}

	// Sort resources.
	resources := make([]string, 0, len(byResource))
	for r := range byResource {
		resources = append(resources, r)
	}
	sort.Strings(resources)

	// Totals.
	totalImpl, totalDoc := 0, 0
	for _, rg := range byResource {
		totalImpl += rg.implemented
		totalDoc += rg.total
	}
	pct := 0
	if totalDoc > 0 {
		pct = totalImpl * 100 / totalDoc
	}

	summary := fmt.Sprintf("CLI implements %d of %d documented endpoint patterns (%d%%)", totalImpl, totalDoc, pct)
	fmt.Println(summary)
	fmt.Println()

	// Print top gaps (most missing first).
	type gapEntry struct {
		resource string
		gap      int
	}
	var gaps []gapEntry
	for _, r := range resources {
		rg := byResource[r]
		if len(rg.missing) > 0 {
			gaps = append(gaps, gapEntry{r, len(rg.missing)})
		}
	}
	sort.Slice(gaps, func(i, j int) bool { return gaps[i].gap > gaps[j].gap })

	fmt.Println("Top resource areas with unimplemented documented endpoints:")
	for _, g := range gaps {
		rg := byResource[g.resource]
		fmt.Printf("  %-40s %d missing / %d total\n", g.resource, g.gap, rg.total)
	}

	// Write markdown report.
	var sb strings.Builder
	sb.WriteString("# Canvas CLI Spec Coverage Gap Report\n\n")
	sb.WriteString(fmt.Sprintf("**%s**\n\n", summary))
	sb.WriteString("| Resource | Implemented | Documented | Gap |\n")
	sb.WriteString("|----------|------------|------------|-----|\n")
	for _, r := range resources {
		rg := byResource[r]
		sb.WriteString(fmt.Sprintf("| %s | %d | %d | %d |\n", r, rg.implemented, rg.total, len(rg.missing)))
	}
	sb.WriteString("\n## Missing Endpoints (documented but not implemented)\n\n")
	for _, r := range resources {
		rg := byResource[r]
		if len(rg.missing) == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("### %s\n\n", r))
		for _, m := range rg.missing {
			sb.WriteString(fmt.Sprintf("- `%s`\n", m))
		}
		sb.WriteString("\n")
	}

	if err := os.WriteFile(coverageOut, []byte(sb.String()), 0o644); err != nil { // #nosec G306 -- coverage report, world-readable by design
		return err
	}
	fmt.Printf("\nFull report written to %s\n", coverageOut)
	return nil
}

func loadManifest() (*Manifest, error) {
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w (run `make spec-sync` first)", manifestPath, err)
	}
	var man Manifest
	if err := json.Unmarshal(data, &man); err != nil {
		return nil, err
	}
	if len(man.Endpoints) == 0 {
		return nil, fmt.Errorf("manifest has no endpoints \u2014 run `make spec-sync`")
	}
	return &man, nil
}

// firstSegment returns the first path segment after /api/v1/ (or /api/lti/).
func firstSegment(path string) string {
	for _, prefix := range []string{"/api/v1/", "/api/lti/"} {
		if after, ok := strings.CutPrefix(path, prefix); ok {
			seg, _, _ := strings.Cut(after, "/")
			return seg
		}
	}
	// Fallback: last non-empty segment.
	parts := strings.Split(strings.Trim(path, "/"), "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return path
}
