package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// --- Claude Code ---

func emitCanvasClaudeCode(cmd *cobra.Command, g canvasGuardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctCanvasVerbs(g.asked())

	deny := []string{}
	for _, v := range blocked {
		deny = append(deny, fmt.Sprintf("Bash(canvas * %s:*)", v))
	}
	// Also hard-block the raw-api escape for known destructive HTTP methods.
	deny = append(deny, "Bash(canvas api DELETE:*)", "Bash(canvas api PUT:*)", "Bash(canvas api POST:*)")
	if len(blocked) > 0 {
		deny = append(deny, "mcp__.*canvas.*_"+canvasVerbGroup(blocked))
	}

	ask := []string{}
	for _, v := range asked {
		ask = append(ask, fmt.Sprintf("Bash(canvas * %s:*)", v))
	}
	if len(asked) > 0 {
		ask = append(ask, "mcp__.*canvas.*_"+canvasVerbGroup(asked))
	}

	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/canvas-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{"deny": deny, "ask": ask},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__.*canvas.*")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Claude Code agent-safety config. The MCP-tool branch of the hook is a hard")
	fmt.Fprintln(out, "# block (structured tool names can't be obfuscated); the Bash branch is")
	fmt.Fprintln(out, "# best-effort — it defeats quote/backslash tricks but not variable")
	fmt.Fprintln(out, "# indirection or shell aliases, so MCP-only operation (or a read-only")
	fmt.Fprintln(out, "# sandbox) is the strongest guarantee. The permission rules are")
	fmt.Fprintln(out, "# belt-and-suspenders. The 'canvas api' escape hatch is partially covered")
	fmt.Fprintln(out, "# (DELETE/PUT/POST patterns) but can bypass verb classification — prefer")
	fmt.Fprintln(out, "# MCP-only operation for a hard guarantee. Regenerate after upgrading.")
	fmt.Fprintln(out)
	if err := canvasWriteOrPrint(cmd, write, canvasHookScriptPath(write), canvasHookScript(blocked), 0o755); err != nil {
		return err
	}
	fmt.Fprintln(out)
	return canvasWriteOrPrint(cmd, write, canvasClaudeSettingsPath(write), string(settingsJSON)+"\n", 0o644)
}

func canvasHookScriptPath(write bool) string {
	if write {
		return filepath.Join(".claude", "hooks", "canvas-guard.sh")
	}
	return ".claude/hooks/canvas-guard.sh"
}

func canvasClaudeSettingsPath(write bool) string {
	if write {
		return filepath.Join(".claude", "settings.json")
	}
	return ".claude/settings.json"
}

func canvasHookScript(blocked []string) string {
	vg := canvasVerbGroup(blocked)
	return `#!/usr/bin/env bash
# canvas agent guard — blocks irreversible canvas operations on the Bash and MCP
# surfaces. Generated by ` + "`canvas agent guard`" + `; regenerate after
# upgrading canvas so new actions are covered.
#
# The MCP-tool branch is a hard block. The Bash branch is best-effort: it defeats
# quote/backslash obfuscation (e.g. ` + "`canvas courses de\"\"lete 1`" + `) but NOT
# variable indirection (` + "`a=delete; canvas courses $a 1`" + `) or shell aliases.
# The "canvas api" escape hatch bypasses verb classification entirely — run agents
# MCP-only or in a read-only sandbox for a hard guarantee.
verbs='` + vg + `'
input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq, no interpolation
# -> always valid JSON). Used by the no-jq fallback.
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# Without jq we cannot isolate the tool name. Fail safe, not open: scan the raw
# payload (newlines flattened) for an irreversible canvas verb and deny if
# present, rather than silently allowing everything. Also catch raw-api
# destructive HTTP methods.
if ! command -v jq >/dev/null 2>&1; then
  flat=$(printf '%s' "$input" | tr '\n' ' ')
  if printf '%s' "$flat" | grep -qiE "canvas.*${verbs}"; then
    deny_raw "canvas agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  if printf '%s' "$flat" | grep -qiE "canvas api.*(DELETE|PUT|POST)"; then
    deny_raw "canvas agent guard: destructive raw-api call blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason so an interpolated value (e.g.
# a tool name) can never break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    # Also test with quotes/backslashes stripped to defeat trivial obfuscation
    # such as ` + "`canvas courses de\"\"lete 1`" + ` (\042=" \047=' \134=\), and
    # flatten newlines so a verb split across lines can't slip past the
    # line-oriented grep.
    stripped=$(printf '%s' "$cmd" | tr -d '\042\047\134')
    if printf '%s\n%s' "$cmd" "$stripped" | tr '\n' ' ' | grep -qiE "\bcanvas\b.*\b${verbs}\b"; then
      deny "canvas agent guard: irreversible operation blocked (${verbs})."
    fi
    # Catch "canvas api DELETE/PUT/POST ..." patterns (raw-api escape hatch).
    if printf '%s\n%s' "$cmd" "$stripped" | tr '\n' ' ' | grep -qiE "\bcanvas\b.*\bapi\b.*(DELETE|PUT|POST)"; then
      deny "canvas agent guard: destructive raw-api call blocked. Use dedicated commands or MCP-only mode."
    fi
    ;;
  mcp__*canvas*)
    if printf '%s' "$tool" | grep -qiE "_${verbs}$"; then
      deny "canvas agent guard: irreversible MCP tool blocked (${tool})."
    fi
    ;;
esac
exit 0
`
}

// --- Codex ---

func emitCanvasCodex(cmd *cobra.Command, g canvasGuardPlan, write bool) error {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Codex agent-safety config (~/.codex/config.toml).")
	fmt.Fprintln(out, "# Codex has no per-command deny hook: read-only sandbox is the hard block.")
	fmt.Fprintln(out, "# Canvas MCP tools that are destructive already require approval when the")
	fmt.Fprintln(out, "# approval policy is set to 'untrusted'.")
	fmt.Fprintln(out)
	mode := "read-only"
	policy := "untrusted"
	note := "# read-only sandbox + untrusted: writes pause for approval; reads run free.\n" +
		"# Switch sandbox_mode to \"workspace-write\" only if you accept unattended writes."
	if g.allWrites {
		note = "# read-only sandbox: no canvas write can run without an explicit approval."
	}
	content := fmt.Sprintf("sandbox_mode    = %q\napproval_policy = %q\n\n%s\n", mode, policy, note)
	return canvasWriteOrPrint(cmd, write, canvasCodexConfigPath(write), content, 0o644)
}

func canvasCodexConfigPath(write bool) string {
	if write {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".codex", "config.toml")
		}
	}
	return "~/.codex/config.toml"
}

// --- OpenCode ---

func emitCanvasOpenCode(cmd *cobra.Command, g canvasGuardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctCanvasVerbs(g.asked())

	bash := map[string]any{"*": "allow"}
	perm := map[string]any{}
	for _, v := range blocked {
		bash["canvas * "+v+"*"] = "deny"
		perm["canvas_*_"+v] = "deny"
	}
	// Block destructive raw-api calls.
	bash["canvas api DELETE*"] = "deny"
	bash["canvas api PUT*"] = "deny"
	bash["canvas api POST*"] = "deny"

	for _, v := range asked {
		bash["canvas * "+v+"*"] = "ask"
		perm["canvas_*_"+v] = "ask"
	}
	perm["bash"] = bash

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perm,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# OpenCode agent-safety config (opencode.json). `deny` is a hard block;")
	fmt.Fprintln(out, "# `ask` prompts. The specific canvas patterns take precedence over the `*`")
	fmt.Fprintln(out, "# catch-all, which allows everything else. Destructive raw-api HTTP methods")
	fmt.Fprintln(out, "# (DELETE/PUT/POST) are also blocked on the Bash surface.")
	fmt.Fprintln(out)
	return canvasWriteOrPrint(cmd, write, canvasOpenCodeConfigPath(), string(b)+"\n", 0o644)
}

func canvasOpenCodeConfigPath() string {
	return "opencode.json"
}

// canvasGuardHosts returns the list of known host identifiers for completion.
// It is exported as a helper for tests.
func canvasGuardHosts() []string {
	return []string{"claude-code", "codex", "opencode"}
}

// formatCanvasGuardRules returns a human-readable summary of what will be
// blocked or asked for a given plan. Used in tests and debug output.
func formatCanvasGuardRules(g canvasGuardPlan) string {
	var sb strings.Builder
	blocked := g.blocked()
	asked := g.asked()
	fmt.Fprintf(&sb, "blocked: %d commands; asked: %d commands\n", len(blocked), len(asked))
	for _, c := range blocked {
		fmt.Fprintf(&sb, "  BLOCK %s\n", c.cli)
	}
	for _, c := range asked {
		fmt.Fprintf(&sb, "  ASK   %s\n", c.cli)
	}
	return sb.String()
}
